### ISSUE TITLE
Trying to set up a kit and getting null?

### ISSUE THREAD

**Issue by weltandmelt** [KaiKikuchi/BetterKits#2]
http://pastebin.com/sLJHHYLk

**Comment by leelawd** [comment]
Just got this error as well and looking back through the fml-server log i found this, http://pastebin.com/ywhTiHeH

**Comment by KaiKikuchi** [comment]
Hey, thank you for your reports!

It looks like you get that error if you run it on Linux OSes.
@weltandmelt can you confirm it?

**Comment by KaiKikuchi** [comment]
Fixed in version 0.9.3. Thank you very much for your reports!

**Comment by weltandmelt** [comment]
im not using linux, also.

**Comment by KaiKikuchi** [comment]
I was getting the error on linux only. It was working fine under windows. Anyway is the issue fixed on v.0.9.3?

**Comment by weltandmelt** [comment]
i am not sure, havent been able to get to it, but i just read that i need a plugins folder for it to be in and not the mods folder.

**Comment by KaiKikuchi** [comment]
Uh no, don't worry. You can put the jar in your mods folder too. It'll work anyway.

**Comment by weltandmelt** [comment]
ok, i will try it and let you know

**Comment by weltandmelt** [comment]
Im working on launching, but someone said i had to do this because its for pixelmon.

**Comment by weltandmelt** [comment]
http://pastebin.com/AwTBXGzp  i get that now when i try it

**Comment by KaiKikuchi** [comment]
You're running an old version of Sponge. You should upgrade to Sponge 1.10.2 and Pixelmon for Forge 1.10.2!

**Comment by weltandmelt** [comment]
im running pixelmon on 1.8 though

**Comment by weltandmelt** [comment]
is there a 1.8.9 version?

**Comment by KaiKikuchi** [comment]
Sponge for 1.8 is unsupported and lacks a lot of things, like the Inventory API. That is why BetterKits doesn't work on your 1.8 server, and can't work with that because of the lack of the Inventory API on Sponge 1.8.9.

I am sorry about that, and I am a bit disappointed about the lack of the Inventory API on 1.8.9!

I heard that Pixelmon for 1.10.2 is stable, and I think that players are looking forward to play on 1.10.2 servers. You may want to consider that!
